version: "3.1"

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
    command: python wsgi.py
    restart: always
    environment:
      PORT: 80
    env_file:
      - ".env"
    volumes:
     - .:/src
