"""empty message

Revision ID: 967fa33fcdfe
Revises: b3392ae97a47
Create Date: 2021-10-27 09:59:47.404215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967fa33fcdfe'
down_revision = 'b3392ae97a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_categories_limits_asc', sa.Column('limit_year_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_categories_limits_asc', 'limit_year_number')
    # ### end Alembic commands ###
